### ISSUE TITLE
NewLib variants do not build on aarch64

### ISSUE THREAD

**Issue by dleslie** [andwn/marsdev#10]
This  is because the ancient version used isn't aware of this architecture.

#9 fixes the issue by bumping the version to the latest.

**Comment by dleslie** [comment]
Hmm, only the 32x example displays anything and it's flickering; gens-plus-gx crashes, and picodrive worked. Perhaps there's more to fix.

**Comment by andwn** [comment]
My memory is fuzzy but a couple years ago i tried to upgrade newlib to see what would happen and recall every genesis project i have either failing to build or run until i put the old version back. Most of the examples should not even be including newlib though.

**Comment by andwn** [comment]
Another issue on arm before you find out: Samples get corrupted because wavtoraw and xgmtool are not endian agnostic

**Comment by dleslie** [comment]
Closing this. Best just to use x86 toolchain in a docker image.
