### ISSUE TITLE
Doesnt work on SGDK 1.51 (Ubuntu)?

### ISSUE THREAD

**Issue by valdirSalgueiro** [andwn/marsdev#2]
Hello it compiles fine no error(besides renaming some stuff on examples to make it compatible with last SGDK). When i load up the rom it doesnt look like any stuff is uploaded like palette, tiles etc and i get garbage on screen.

I am using last ubuntu 20.04 if that matters.

btw this is my log file when i run "make" on marsdev

`make -C toolchain ARCH=m68k
make[1]: Entering directory '/home/valdirsalgueiro/pvt/marsdev/toolchain'
+++ Building binutils-2.33.1 for m68k...
cd binutils-2.33.1/build && \
        ../configure --target=m68k-elf --prefix=/home/valdirsalgueiro/mars/m68k-elf --with-cpu=m68000 \
        --enable-install-libbfd --enable-shared=no --disable-nls --disable-werror \
        > /home/valdirsalgueiro/pvt/marsdev/toolchain/binutils-m68k.log 2>&1
make -C binutils-2.33.1/build all install-strip \
        >> /home/valdirsalgueiro/pvt/marsdev/toolchain/binutils-m68k.log 2>&1
+++ Building gcc-9.2.0 for m68k...
cd gcc-9.2.0 && ./contrib/download_prerequisites \
        > /home/valdirsalgueiro/pvt/marsdev/toolchain/gcc-m68k.log 2>&1
cd gcc-9.2.0/build && \
        ../configure --target=m68k-elf --prefix=/home/valdirsalgueiro/mars/m68k-elf \
        --enable-languages=c --with-cpu=m68000 \
        --without-headers --disable-libssp \
        --disable-threads --disable-tls --disable-multilib \
        --enable-shared=no --disable-nls --disable-werror \
        >> /home/valdirsalgueiro/pvt/marsdev/toolchain/gcc-m68k.log 2>&1
make -C gcc-9.2.0/build all install-strip \
        >> /home/valdirsalgueiro/pvt/marsdev/toolchain/gcc-m68k.log 2>&1
make[1]: Leaving directory '/home/valdirsalgueiro/pvt/marsdev/toolchain'`

i had to build the other stuff separatedly

thx!

**Comment by andwn** [comment]
I haven't gotten a chance to update SGDK yet, but when I do it's very likely I'll run into this problem and have to fix it. That'll most likely be pretty soon, I just got a new 32MB cart to play with the SSF2 mapper.

I've also had an issues with GCC 9.2.0 over-optimizing things and causing garbled graphics. Not saying that's the cause of your problem but I'm suspicious.

**Comment by andwn** [comment]
Well, finally gave this a try and I'm getting garbled graphics using SGDK master, even when using debug. The location of the graphic symbols seems to be overlapping the start of the ROM.

```
00000000 A __DYNAMIC
00000000 A _sdata
00000000 t _Start_Of_Rom
00000000 t _Vecteurs_68K
00000000 n moon_map_data
00000000 n moon_palette_data
00000020 n sgdk_logo_palette_data
00000040 n font_pal_default_data
00000060 N stop_xgm
00000080 n moon_tileset_data
00000100 t _Rom_Header
00000200 t _Entry_Point
```

Now to figure out why the resources get thrown at the beginning (linker is doing it?)

**Comment by andwn** [comment]
Oh shoot, Stef changed the linker script
https://github.com/Stephane-D/SGDK/commit/cc43e0d57ec1c2acf0751c5d6dca7faa6211a3b9

And what do you know, after updating that it works. New commit soon
