### ISSUE TITLE
Compilation of Marsdev freezing on Mac OS 10.14 Mojave

### ISSUE THREAD

**Issue by AnthonyDev-Git** [andwn/marsdev#25]
When I was trying to compile Marsdev on my Macbook Pro (2015) via the instructions its seems to crash the compilation process of the terminal itself, had I noticed this when it took ages for it to move to the next step. I also noticed this issue when trying to install GCC (which is unrelated to this) and had the same hanging issue.

**Comment by andwn** [comment]
GCC is huge and takes a very long time to build. Tail the log from another terminal to see if it is still running. Also, prevent your computer from sleeping with caffeinate

**Comment by AnthonyDev-Git** [comment]
Alright, thanks!
