### ISSUE TITLE
Building C for Genesis with newlib results in a broken ROM

### ISSUE THREAD

**Issue by DUSTINODELLOFFICIAL** [andwn/marsdev#26]
This is the 2022.02 release binaries on linux. Can be reproduced by simply compiling the md-skeleton example with the makefile modified for newlib (I removed -nostdlib, uncommented the -lnosys line). Loading the resulting out.bin in a hex editor shows 0xF0 bytes of random code located before the vector table.

Snippet of symbols.txt showing the relevant bits:
```
00000000 b 
00000000 t deregister_tm_clones
00000000 A __DYNAMIC
00000000 b __FRAME_END__
00000026 t register_tm_clones
00000054 A _sdata
0000005c t __do_global_dtors_aux
000000cc t call___do_global_dtors_aux
000000ce t frame_dummy
000000ee t call_frame_dummy
000000f0 t RomStart
000001f0 t RomHeader
000002f0 t _start
00000308 t NoTMSS
```
This is using the md.ld linkscript that comes with the toolchain.

Some googling tells me those symbols (deregister_tm_clones etc) are related to GCC internals regarding C++ which is more confusing as this is a C program. I don't know if this is a bug or a misunderstanding on my part about newlib: I want a barebones setup without SGDK, but I need some library functions.

**Comment by andwn** [comment]
Don't remove -nostdlib. -lnosys replaces the standard library

**Comment by DUSTINODELLOFFICIAL** [comment]
This solves the original problem, but now I'm getting undefined references to libc functions. I compiled the zlib library and here's what I get when I try to link with it. Are there any other libs I need to bring in?

```
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: /home/dustin/mars/m68k-elf/m68k-elf/lib/libz.a(inflate.o): in function `updatewindow':
inflate.c:(.text+0x10a): undefined reference to `memcpy'
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: inflate.c:(.text+0x168): undefined reference to `memcpy'
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: inflate.c:(.text+0x1ac): undefined reference to `memcpy'
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: /home/dustin/mars/m68k-elf/m68k-elf/lib/libz.a(inflate.o): in function `inflate':
inflate.c:(.text+0xb0c): undefined reference to `memcpy'
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: inflate.c:(.text+0xfd6): undefined reference to `memcpy'
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: /home/dustin/mars/m68k-elf/m68k-elf/lib/libz.a(inflate.o):inflate.c:(.text+0x1e4e): more undefined references to `memcpy' follow
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: /home/dustin/mars/m68k-elf/m68k-elf/lib/libz.a(zutil.o): in function `zcalloc':
zutil.c:(.text+0x3a): undefined reference to `malloc'
/home/dustin/mars/m68k-elf/bin/../lib/gcc/m68k-elf/10.3.0/../../../../m68k-elf/bin/ld: /home/dustin/mars/m68k-elf/m68k-elf/lib/libz.a(zutil.o): in function `zcfree':
zutil.c:(.text+0x48): undefined reference to `free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:92: out.elf] Error 1
```

**Comment by DUSTINODELLOFFICIAL** [comment]
Adding -lc to the linker command fixes that but gives me errors about sbrk missing. I feel like I'm misunderstanding something fundamental here...

**Comment by andwn** [comment]
I'm not sure why memcpy wouldn't be in nosys, but it makes sense that malloc isn't. I think for that you are best off copying memory.c from SGDK and renaming MEM_alloc to malloc and MEM_free to free. I think memcpy/memset are in there too, but in memory_a.s

**Comment by DUSTINODELLOFFICIAL** [comment]
-nostdlib disables all libraries, even libc from the looks of it

They can be added back in, but apparently the order matters. "-lc -lnosys -lz" links OK.

I don't know whether or not to close this, as there is probably a better way to fix the initial problem than the -nostdlib switch?

**Comment by andwn** [comment]
-nostartfiles perhaps? It's been a while since I messed with this stuff and don't use newlib in my own projects so...

**Comment by andwn** [comment]
Looks like using -nostartfiles instead of -nostdlib is the answer here. Making a separate newlib sample that does this.

**Comment by andwn** [comment]
Got the working newlib sample up so closing
