### ISSUE TITLE
Trying to compile genesis rom on Mac (Visual Studio Code) returns error 1: can't open boot.s for reading: No such file or dir.

### ISSUE THREAD

**Issue by NULLMODEN1299** [andwn/marsdev#27]
When I try to compile the template project that comes with the SGDK the compiler gives a assembler error:
Error: can't open boot.s for reading: No such file or directory
make: *** [boot.o] Error 1

I've set all of my paths correctly for mars and sgdk and yet I still get this issue.

Here is the console output.
```
Anthonys-MBP:genesisproject <username>$ export MARSDEV=~/mars
Anthonys-MBP:genesisproject <username>$ make    clean release
rm -f src/main.o   out.bin out.elf symbol.txt boot.o
Anthonys-MBP:genesisproject <username>$ export MARSDEV=~/mars
Anthonys-MBP:genesisproject <username>$ make    clean release
rm -f src/main.o   out.bin out.elf symbol.txt boot.o
rm -rf asmout
/Users/<username>/mars/m68k-elf/bin/m68k-elf-as -m68000 --register-prefix-optional boot.s -o boot.o
Assembler messages:
Error: can't open boot.s for reading: No such file or directory
make: *** [boot.o] Error 1
```
Here is a picture of the configuration for the Genesis extension.
<img width="967" alt="Screen Shot 2022-05-28 at 23 46 29" src="https://user-images.githubusercontent.com/106459784/170851172-aa9e301c-0f2d-4394-8a2d-f2370fec0d1c.png">

**Comment by andwn** [comment]
Vanilla SGDK organizes projects differently than gendev/marsdev do. Our template projects are not compatible with each other

**Comment by NULLMODEN1299** [comment]
Oh... that makes sense. Thanks for the help!
