### ISSUE TITLE
Download script attempts to write to ~/mars

### ISSUE THREAD

**Issue by MVittiS** [andwn/marsdev#31]
When invoking the initial step in the "complete toolchain" part of the [Installation Guide](https://github.com/andwn/marsdev/blob/master/doc/install.md), the script attempts to copy the downloaded tarballs to ~/mars, which doesn't exist on this machine, nor was it specified in the guide.

```
$marsdev > make m68k-toolchain-newlib LANGS=c,c++ -j3
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C toolchain all-newlib ARCH=m68k
--2022-10-13 22:24:02--  https://tenshi.skychase.zone/newlib-4.2.0.20211231.tar.gz
--2022-10-13 22:24:02--  https://tenshi.skychase.zone/gcc-12.2.0.tar.xz
--2022-10-13 22:24:02--  https://tenshi.skychase.zone/isl-0.24.tar.bz2
(...)
mpfr-4.1.0.tar.xz: OK
cp -rf ldscripts/ /Users/{username}/mars/ldscripts
cp: /Users/{username}/mars/ldscripts: No such file or directory
cp: ldscripts/: unable to copy extended attributes to /Users/{username}/mars/ldscripts: No such file or directory
cp: /Users/{username}/mars/ldscripts/md.ld: No such file or directory
cp: /Users/{username}/mars/ldscripts/mars.ld: No such file or directory
cp: /Users/{username}/mars/ldscripts/sgdk.ld: No such file or directory
make[1]: *** [/Users/{username}/mars/ldscripts] Error 1
make[1]: *** Waiting for unfinished jobs....
gcc-12.2.0.tar.xz    70%[=============>      ]  57.24M  11.6MB/s    eta 3s     200 OK
(...)
gcc-12.2.0.tar.xz: OK
binutils-2.39.tar.xz: OK
make: *** [m68k-toolchain-newlib] Error 2
```

Machine info:
OS: macOS 12.3.1, x86_64
`xcode-select --version`: 2395
Brew installed: yes

**Comment by andwn** [comment]
It's the default install location, but it looks like I forgot to copy that info into the new install guide after the refactor last week, sorry about that. It can be changed by specifying MARSDEV=/some/where/else

A step that writes to it ran before the step that creates it because I still have to fix parallel building (of the toolchain itself, but gcc and binutils are passed -j).

**Comment by andwn** [comment]
Current version uses a "work" directory within the repository root instead of doing anything with home, so closing this.
