### ISSUE TITLE
Unable to compile md-skeleton and marsdev install location wrong

### ISSUE THREAD

**Issue by Retro-Hax** [andwn/marsdev#41]
Hello so i decided to start off with the install location issue basically i have done this
```
export MARS_INSTALL_DIR=/opt/mars
```
but ls into that location it cannot find anything and looking at /opt/ also just shows no mars folder or a toolchain folder as well as even touching nothing and not even doing an EXPORT and installing mars in the default location results in no folder being generated itll always be generated in where marsdev itself is located in which in my case is this
```
/home/retro-hax/Retro-Hax/Homebrew/Genesis/Tools/marsdev/mars/m68k-elf/bin
```

which also causes a second issue that is even weirder regarding me being unable to compile this example called md-skeleton or even any md- example
```
[retro-hax@archlinux md-skeleton]$ make
make: /mnt/Samsung4TB/Retro-Hax/Homebrew/Genesis/Tools/marsdev_install/m68k-elf/bin/m68k-elf-gcc: No such file or directory
CC src/error.c
make: /mnt/Samsung4TB/Retro-Hax/Homebrew/Genesis/Tools/marsdev_install/m68k-elf/bin/m68k-elf-gcc: No such file or directory
make: *** [Makefile:90: src/error.o] Error 127
```
now i do not at all have ever pointed the m8k binary to this so this entire Thing is very confusing and if i have not given enough please tell me and ill gladly add more it is just very frustrating for me :(

**Comment by andwn** [comment]
What commands did you run after the export, and what was their output? "make" by itself will build marsdev into a local "work" directory but it will not be installed until you run "sudo make install". This separation was made because compiling a program should not be a privileged task, but installing software is.

**Comment by Retro-Hax** [comment]
Ah alright so uh i now did install marsdev via sudo make install tho it still puts it into /opt/toolchains/mars and regarding the export uh what do you mean exactly? since i wrote multiple exports in the issue basically after marsdev compiled succesfully with m68k-toolchain-newlib i added like it told me to the binary to my path
```
/home/retro-hax/Retro-Hax/Homebrew/Genesis/Tools/marsdev/mars/m68k-elf/bin
```
and i changed nothing inside any of those Makefiles

**Comment by andwn** [comment]
I mean the one and only command that starts with "export" you wrote at the top of your issue. At any rate, it seems that make does not use the same environment variables as Bash, so it's better to append to the end of the make commands.

Here is my full install process on Debian:

```
andy@rumia:~/repos$ sudo apt install build-essential git texinfo openjdk-11-jre libpng-dev
[...]

andy@rumia:~/repos$ git clone https://github.com/andwn/marsdev
Cloning into 'marsdev'...
[...]

andy@rumia:~/repos$ cd marsdev

andy@rumia:~/repos/marsdev$ make m68k-toolchain sgdk
[...zzz...]

andy@rumia:~/repos/marsdev$ sudo make install MARS_INSTALL_DIR=/opt/mars
cp -rf /home/andy/repos/marsdev/mars/* /opt/mars
--------------------------------------------------------------------------------
Marsdev has been installed to /opt/mars.
Run the following to set the proper environment variables before building your projects:
source /opt/mars/mars.sh
--------------------------------------------------------------------------------

andy@rumia:~/repos/marsdev$ cat /opt/mars/mars.sh
#!/bin/sh
export MARSDEV=/opt/mars
export GDK=/opt/mars/m68k-elf
export PATH="$PATH:/opt/mars/m68k-elf/bin"
export PATH="$PATH:/opt/mars/sh-elf/bin"

andy@rumia:~/repos/marsdev$ /opt/mars/mars.sh

andy@rumia:~/repos/marsdev$ cd examples/md-skeleton

andy@rumia:~/repos/marsdev/examples/md-skeleton$ make
CC src/error.c
CC src/main.c
CC src/string.c
CC src/vdp.c
AS src/boot.s
AS src/font.s
Linking out.elf
Stripping ELF header...
1+1 records in
2+0 records out
16384 bytes (16 kB, 16 KiB) copied, 6.534e-05 s, 251 MB/s
Creating symbol.txt
rm src/vdp.o src/font.o src/string.o src/boot.o src/main.o src/error.o out.elf
```
![image](https://github.com/andwn/marsdev/assets/8164394/de07eac1-5ff0-4cbe-afc6-3e717308b878)

(I also noticed a bug when using "make" by itself, it compiles things in the wrong order, will fix it later on)

**Comment by Retro-Hax** [comment]
alright so i fixed it i was just too dumb to run source /opt/toolchains/mars/mars.sh before building the md-skeleton project sorry :(

**Comment by Retro-Hax** [comment]
Im sorry for bumping the thread again after several months of silence but i have an issue with Install basically i have here is the log of where it installs marsdev too
```
Toolchain installed to /home/retro-hax/Retro-Hax/Homebrew/MegaDrive/Tools/marsdev/mars/sh-elf.
Add /home/retro-hax/Retro-Hax/Homebrew/MegaDrive/Tools/marsdev/mars/sh-elf/bin to your PATH before building projects.
make[1]: Leaving directory '/home/retro-hax/Retro-Hax/Homebrew/MegaDrive/Tools/marsdev/sh-gcc-toolchain'
[sudo] password for retro-hax: 
cp -rf /home/retro-hax/Retro-Hax/Homebrew/MegaDrive/Tools/marsdev/mars/* /opt/toolchains/mars
--------------------------------------------------------------------------------
Marsdev has been installed to /opt/toolchains/mars.
Run the following to set the proper environment variables before building your projects:
source /opt/toolchains/mars/mars.sh
--------------------------------------------------------------------------------
```
even tho in my .bashrc file i put it like this
```
source /etc/bash.bashrc

export MARS_INSTALL_DIR=/opt/mars/
```
and i already restarted my pc so that this change takes effect and it still does not :(

**Comment by andwn** [comment]
sudo make install MARS_INSTALL_DIR=/opt/mars

**Comment by Retro-Hax** [comment]
Sorry for the late reply but just wanted to say it works!
